server:
  port: 8081
  servlet:
    context-path: /mini-mart

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/mini_mart_db1}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second