server:
  port: 8081

spring:
  datasource:
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/mini_mart_db_1}
    url: "jdbc:mysql://localhost:3306/mini_mart_db_1"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
          host: localhost
          port: 6379
          # password: your-redis-password # Nếu Redis server của bạn có mật khẩu

api:
  prefix: /api/v1

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second 432 000 (5day)
