server:
  port: 8081

spring:
  datasource:
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/shopclothing}
    url: "jdbc:mysql://localhost:3306/shopclothing"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
api:
  prefix: /api/v1

jwt:
  signerKey: QcACku/+MCwysAVv/s7cSW9J1ZdO0HkSBZrXUfYRa21I+B91ka1ZqmhBcCX8zZdg
  valid-duration: 7200 #in second (2 hour)
  refreshable-duration: 432000 #in second 432 000 (5day)
